# num_classes: 91
# remap_mscoco_category: True

train_dataloader: 
  dataset: 
    return_masks: False
    transforms:
      ops: ~ 
  shuffle: True
  batch_size: 4
  num_workers: 4
  collate_fn: default_collate_fn


val_dataloader:
  dataset: 
    transforms:
      ops: ~
  shuffle: False
  batch_size: 8
  num_workers: 4
  collate_fn: default_collate_fn
