__include__: [
  '../dataset/coco_detection_custom.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer_custom.yml',
  './include/rtdetr_r50vd.yml',
]

output_dir: ./output/rtdetr_r50vd_6x_coco
